# basic options
title: 5atoshiNakamoto
author: 5atoshiNakamoto
email: 5atoshiNakamoto+Github@simplelogin.com
description: 5atoshiNakamoto's Warrant Canary Archive

# Build settings
markdown: kramdown
theme: minima
